rgname              = "azure-tf-dev"
rglocation          = "eastus"
vnet_name           = "azvnet-dev"
vnet_cidr_prefix    = "10.0.0.0/16"
subnet_name         = "aztfsubnet-dev"
subnet_cidr_prefix  = "10.0.1.0/24"